language: python

python:
  - "2.7"

sudo: false

virtualenv:
  system_site_packages: true

cache:
  directories:
    - $HOME/.cache/pip


addons:

  apt:

    sources:

      - ubuntu-toolchain-r-test
      - kubuntu-backports
      - couchbase-precise

    packages:

      - libopenmpi-dev
      - openmpi-bin
      - libhdf5-openmpi-dev

      # Python stuff
      # (for discovering these packages set in virtualenv: system_site_packages: true)
      - python-numpy
      - python-mpi4py
      - python-h5py


#before_install:

install:
# Install h5writer
  - cd $HOME/build/mhantke/h5writer
  - python setup.py install

script:
# Test examples
  - cd $HOME/build/mhantke/h5writer/examples; python test.py
  - cd $HOME/build/mhantke/h5writer/examples; mpirun -n 6 python test.py